# backend
backend:
  name: chackhadio-nextjs
  replicaCount: 1
  image:
    repository: "sororiri/chackhadio"
    tag: 27
# ingress
ingress:
  backend:
    host: www.chakanifilm.com
namespace: chackhadio
